docs: add gitbar app
tauri-apps/awesome-tauri pull request #104
Opened 2022-11-19 13:35 UTC by mikaelkristiansson

This is the link to the project: [GitBar](https://github.com/mikaelkristiansson/gitbar)

- [ ] **I have read the [contributing guidelines](contributing.md).**
- [ ] Use the following format: `[Title](link) - Description.`
- [ ] Add entries to the bottom of the correct category.
- [ ] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [ ] Description does not start with `A` or `An`.
- [ ] Description is under 24 words.
- [ ] Description has no links or parenthesis.
- [ ] Use `backticks` when mentioning package names.
- [ ] Double-check spelling and grammar.
- [ ] No trailing whitespace is added to the end of any file.
- [ ] One suggestion per pull request.
- [ ] I understand that my entry will be removed if it violates the guidelines.
- [ ] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

2022-11-19 13:37 UTC, mikaelkristiansson commented
This is my first Tauri app, and I really loved creating it! ❤️ 
Hopefully it's a useful app to someone else than just me.

2022-11-19 21:50 UTC, JonasKruckenberg commented
Just one point of feedback regarding your app:
The allowlist option:
```json
"all": true,
```
Overrides all other options, so your config still enables all APIs

2022-11-19 21:51 UTC, JonasKruckenberg requested changes

2022-11-19 21:51 UTC, JonasKruckenberg commented on README.md
> +- [GitBar](https://github.com/mikaelkristiansson/gitbar) - Tray bar app for github reviews
```suggestion
- [GitBar](https://github.com/mikaelkristiansson/gitbar) - System tray app for GitHub reviews.
```

2022-11-19 22:25 UTC, mikaelkristiansson commented
> Just one point of feedback regarding your app: The allowlist option:
> 
> ```json
> "all": true,
> ```
> 
> Overrides all other options, so your config still enables all APIs

Great feedback, I’ll change it 👍

2022-11-19 22:34 UTC, mikaelkristiansson commented
> Just one point of feedback regarding your app: The allowlist option:
> 
> ```json
> "all": true,
> ```
> 
> Overrides all other options, so your config still enables all APIs

https://github.com/mikaelkristiansson/gitbar/pull/9

2022-11-20 08:24 UTC, JonasKruckenberg approved these changes

2022-11-20 08:25 UTC, JonasKruckenberg commented
Alright, thanks for being part of the community 😁

2022-11-20 08:26 UTC, merged