Add tauri-solid-ts-tailwind-vite-template
tauri-apps/awesome-tauri pull request #108
Opened 2022-12-11 12:49 UTC by AR10Dev

This is the link to the project: [tauri-solid-ts-tailwind-vite](https://github.com/AR10Dev/tauri-solid-ts-tailwind-vite)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [x] Works with **Tauri 1.x and onward**.
- [x] The repo is at least 30 days old.
- [x] Documentation is in English.
- [x] The template provides enough information about how to get started and what's included.
- [x] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

2023-01-09 10:41 UTC, JonasKruckenberg requested changes, later dismissed

2023-01-09 10:41 UTC, JonasKruckenberg commented on README.md
> +- [tauri-solid-ts-tailwind-vite-template](https://github.com/AR10Dev/tauri-solid-ts-tailwind-vite) - Solid template with Vite + HMR, TypeScript, Tailwind CSS, ESLint, Prettier, file based routing and
```suggestion
- [tauri-solid-ts-tailwind-vite-template](https://github.com/AR10Dev/tauri-solid-ts-tailwind-vite) - SolidJS Template preconfigured to use Vite, TypeScript, Tailwind CSS, ESLint and Prettier.
```

Adapted your repos README description to shorten this a bit

2023-01-24 21:36 UTC, yannkost commented
Gotta say I have to try this template out, solidjs rocks :) I already say thank you @AR10Dev

2023-02-20 17:00 UTC, FabianLars approved these changes

2023-02-20 17:14 UTC, merged