Added winget-gui
tauri-apps/awesome-tauri pull request #112
Opened 2022-12-29 16:57 UTC by danielehrhardt

This is the link to the project: [Winget GUI](https://github.com/codextde/winget-gui)

- [X ] **I have read the [contributing guidelines](contributing.md).**
- [ X] Use the following format: `[Title](link) - Description.`
- [ X] Add entries to the bottom of the correct category.
- [ X] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [ X] Description does not start with `A` or `An`.
- [ X] Description is under 24 words.
- [ X] Description has no links or parenthesis.
- [ X] Use `backticks` when mentioning package names.
- [ X] Double-check spelling and grammar.
- [ X] No trailing whitespace is added to the end of any file.
- [ X] One suggestion per pull request.
- [ X] I understand that my entry will be removed if it violates the guidelines.
- [ X] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [  Works with **Tauri 1.x and onward**.
- [ X] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [X ] The app is original and not too simple.
- [X ] The README is in English.
- [X ] The app makes a reasonable effort to be fast, lightweight and secure.
- [X ] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

2023-01-09 11:00 UTC, JonasKruckenberg requested changes
You may also consider adding a CSP here https://github.com/codextde/winget-gui/blob/319e5b29da9d401265ea2f90e2c1eb00a3c6be3a/src-tauri/tauri.conf.json#L57
And also get rid of the demo greet command 😄 https://github.com/codextde/winget-gui/blob/319e5b29da9d401265ea2f90e2c1eb00a3c6be3a/src-tauri/src/main.rs#L6-L10

2023-01-09 11:00 UTC, JonasKruckenberg commented on README.md
> +- [Winget GUI](https://github.com/codextde/winget-gui) - Open-source winget gui
```suggestion
- [Winget GUI](https://github.com/codextde/winget-gui) - Open-source winget GUI.
```

2023-01-09 12:29 UTC, danielehrhardt commented
code changes done

2023-01-09 14:11 UTC, JonasKruckenberg approved these changes

2023-01-09 14:15 UTC, JonasKruckenberg commented
Oh actually, we require all commits to be signed across Tauri's repositories. Follow [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) to set up commit signing. Once all the commits in this PR are signed we can merge your contribution. Thanks for being part of our community!

2023-05-10 22:41 UTC, simonhyll commented
@danielehrhardt We have updated the structure of the README a bit. Please update your commit to reflect this change. Also, as already mentioned, all commits need to be signed before we can accept them.

2023-05-11 09:02 UTC, closed without merging