Add Identia to Apps list
tauri-apps/awesome-tauri pull request #19
Opened 2022-02-10 16:51 UTC by iohzrd

- [x] **I have read the [contributing guidelines](contributing.md).**

- [x] Title as described.
- [x] Added to the right category.
- [x] Added to the end of a list.
- [x] The description of your item is a sentence with less than 24 words.
- [x] No links and parentheses in description. 
- [x] The description starts with a capital and ends with a full stop/period.
- [x] The description doesn't start with `A` or `An`.
- [x] No unnecessary words already provided in the context (e.g. `for Tauri`, `a Tauri plugin`).
- [x] Uses proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omits versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`.
- [x] When mentioning package names, uses quotes whenever possible.

### Apps

- [x] The project is Open Source.
- [x] The readme is in English.
- [x] The app is original and not too simple.

2022-02-10 18:53 UTC, JonasKruckenberg requested changes
2 Things:
1. Can you remove those formatting changes from your PR? I assume those are from an editor, maybe save without formatting.
2. Your commit is not signed, so if you could create a signed commit and force push to this branch we can merge the commit!

2022-02-10 21:19 UTC, iohzrd commented
I'll change the formatting, but I'm not sure how to do a signed commit.

2022-02-11 04:27 UTC, iohzrd commented
done

2022-02-11 04:29 UTC, probablykasper approved these changes

2022-02-11 09:51 UTC, JonasKruckenberg approved these changes

2022-02-11 09:53 UTC, merged