feat: add Pointless project
tauri-apps/awesome-tauri pull request #63
Opened 2022-05-08 15:57 UTC by kkoomen

This is the link to the project: [Pointless](https://github.com/kkoomen/pointless)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

2022-05-08 16:07 UTC, JonasKruckenberg requested changes

2022-05-08 16:07 UTC, JonasKruckenberg commented on README.md
> +- [tauri-react-template](https://github.com/oSethoum/tauri-react-template) - React template with Vite, TypeScript, hot module replacement.
If you remove this change we're good!

2022-05-08 21:07 UTC, kkoomen commented on README.md
> +- [tauri-react-template](https://github.com/oSethoum/tauri-react-template) - React template with Vite, TypeScript, hot module replacement.
Done.

2022-05-09 09:57 UTC, JonasKruckenberg approved these changes

2022-05-09 09:57 UTC, merged