[App] - add DevTools-X
tauri-apps/awesome-tauri pull request #93
Opened 2022-10-04 03:10 UTC by Sparkenstein

This is the link to the project: [TITLE](URL)

- [ ] **I have read the [contributing guidelines](contributing.md).**
- [ ] Use the following format: `[Title](link) - Description.`
- [ ] Add entries to the bottom of the correct category.
- [ ] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [ ] Description does not start with `A` or `An`.
- [ ] Description is under 24 words.
- [ ] Description has no links or parenthesis.
- [ ] Use `backticks` when mentioning package names.
- [ ] Double-check spelling and grammar.
- [ ] No trailing whitespace is added to the end of any file.
- [ ] One suggestion per pull request.
- [ ] I understand that my entry will be removed if it violates the guidelines.
- [ ] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

2022-10-04 07:36 UTC, JonasKruckenberg requested changes
Two things of note as well (do with this what you want):

1. `devtools` is not a really great bundle identifier, you should use a domain in reverse notation (ideally a domain you own) to avoid possible collisions. But even `fosslife.devtools` goes a long way to ensure you don't step on anyone's toes.

2. I know it's a devtools app and ppl take security less seriously there, but I can't see a good reason why your app needs ```json
"allowlist": {
   "all": true
}
``` 
Please take a moment to tighten that up.

2022-10-04 07:36 UTC, JonasKruckenberg commented on README.md
> +- [DevTools-X](github.com/fosslife/devtools-x) - Cross-platform collection of development utils, all in one place
```suggestion
- [DevTools-X](https://github.com/fosslife/devtools-x) - Cross-platform collection of development utilities, all in one place.
```

2022-10-04 08:56 UTC, Sparkenstein commented
will change the package identifier that makes sense. 

about allowList I kept it like that because I install npm dependencies very carefully. I especially avoid disputed packages like lodash and all. devtools only has handpicked deps. 
I understand deps of deps can be an issue. so I think I will fix this as well give me till weekend

2023-05-10 22:41 UTC, simonhyll commented
@Sparkenstein We have updated the README structure a bit, please update your commit to reflect this change.

2023-05-11 14:27 UTC, Sparkenstein commented
completely forgot about this. will close this one, and reopen again another.
I am assuming devtools-x goes in productivity section?

2023-05-11 17:19 UTC, simonhyll commented
> completely forgot about this. will close this one, and reopen again another. I am assuming devtools-x goes in productivity section?
> 
> Edit or here https://github.com/tauri-apps/awesome-tauri#developer-tools

@Sparkenstein Good question, I think I'd place it under developer tools :)

2023-05-20 03:58 UTC, closed without merging